// for Login Api Action type

export const LOG_IN_INIT = "LOG_IN_INIT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAIL = "LOG_IN_FAIL";

export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const USER_ROLES_INIT = "USER_ROLES_INIT";
export const USER_ROLES_SUCCESS = "USER_ROLES_SUCCESS";
export const USER_ROLES_FAIL = "USER_ROLES_FAIL";

export const SIGN_OUT = "SIGN_OUT";

// get Corporate User Login History
export const GET_CORPORATE_USER_LOGIN_INIT = "GET_CORPORATE_USER_LOGIN_INIT";
export const GET_CORPORATE_USER_LOGIN_SUCCESS =
  "GET_CORPORATE_USER_LOGIN_SUCCESS";
export const GET_CORPORATE_USER_LOGIN_FAIL = "GET_CORPORATE_USER_LOGIN_FAIL";

// Refresh Token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

// for get all corporate Categories dropdown
export const GET_ALL_CORPORATE_CATEGORIES_INIT =
  "GET_ALL_CORPORATE_CATEGORIES_INIT";
export const GET_ALL_CORPORATE_CATEGORIES_SUCCESS =
  "GET_ALL_CORPORATE_CATEGORIES_SUCCESS";
export const GET_ALL_CORPORATE_CATEGORIES_FAIL =
  "GET_ALL_CORPORATE_CATEGORIES_FAIL";

// For get Bank User Login History Api
export const GET_BANK_USER_LOGIN_INIT = "GET_BANK_USER_LOGIN_INIT";
export const GET_BANK_USER_LOGIN_SUCCESS = "GET_BANK_USER_LOGIN_SUCCESS";
export const GET_BANK_USER_LOGIN_FAIL = "GET_BANK_USER_LOGIN_FAIL";
